map $http_x_forwarded_for $client_ip_for_geo {
    default $remote_addr;
    "~^(?<first_ip>[^, ]+)" $first_ip;
}

geoip2 /etc/nginx/geoip/GeoLite2-Country.mmdb {
    auto_reload 1h;
    $geoip2_country_code source=$client_ip_for_geo country iso_code;
}

server {
    listen 80;

    resolver 127.0.0.11 valid=10s;

    location / {
        if ($geoip2_country_code = "RU") {
            return 403;
        }

        set $upstream http://yandex-music-app:5000;
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}